Iter 15
llravell/go-shortener pull request #15
Opened 2024-11-25 20:40 UTC by llravell

2024-11-25 21:01 UTC, llravell commented on internal/controller/httpv1/httpv1_test.go
> -func sendTestRequest(
Вынес общий код тестов в файл с тестовыми утилитами

2024-11-25 21:04 UTC, llravell commented on internal/usecase/urldelete.go
> +package usecase
Нормально ли такую штуку оформлять как `usecase`? Или это должно быть что-то другое?

2024-11-25 21:08 UTC, llravell commented on internal/usecase/urldelete.go
> +	for item := range ud.urlDeleteItemsCh {
Долго думал как адекватно реализовать оптимальный обработчик очереди для удаления урлов.
Остановился на варианте создавать несколько воркеров чтобы лимитировать запросы к БД.

Но в этом решении не очень нравится что если один юзер будет спамить запросами, то не будет происходить группировки в один запрос

2024-11-25 21:10 UTC, llravell commented on internal/usecase/urldelete.go
> +	ud.urlDeleteItemsCh <- item
Стоит ли здесь добавить проверку на `cancelled` или это может сильно замедлить?

2024-11-28 00:06 UTC, bulbetski requested changes
Хорошая иницатива с чистой архитектурой, да и код в целом хороший. Но раз уж взялся, надо до конца реализовать все слои и сделать корректное разделение.
Так же нужно сделать воркер пул отдельно от юзкейса. Юзкейс отвечает только за бизнес логику

2024-11-28 00:06 UTC, bulbetski commented on internal/app/app.go
> +	usecase.URLDeleteRepo
Если уж хочешь разделить свое приложение на слои, использую репозитории и юзкейсы, то нужно придерживаться немного другой схемы. У тебя должны быть отдельно репозиторий и отдельно юзкейс -- они по сути между собой не связаны

Допустим у тебя будет пакет url.
В нем будут url/usecase и url/repository

Так же не понятно, зачем разделять URLRepo и URLDeleteRepo, почему DeleteMultiple не может быть методом URLRepo? Как будто лишнее усложнение

2024-11-28 00:06 UTC, bulbetski commented on internal/app/app.go
> +	usecase.URLDeleteRepo
Чтобы твоя чистая архитектура была еще чище, надо порефакторить твой service layer. 
В main мы инициализируем репозитории и наши юзкейсы (так называемый инициализационный слой), далее прокидываем их в NewApp(), далее Run() и все остальные методы нашего App работаю только с юзкейсами, они не должны напрямую обращаться к репозиторию -- в этом и суть чистой архитектуры -- логика слоя usecase остается независимой от слоя репозитория и сервиса (аналогично с другими уровнями).

2024-11-28 00:06 UTC, bulbetski commented on internal/controller/httpv1/middleware/auth.go
> +		return ""
Стоит залогировать ошибку

2024-11-28 00:06 UTC, bulbetski commented on internal/controller/httpv1/middleware/auth.go
> +		return ""
Стоит залогировать ошибку

2024-11-28 00:06 UTC, bulbetski commented on internal/controller/httpv1/middleware/auth.go
> +			next.ServeHTTP(w, r)
Стоит залогировать ошибку

2024-11-28 00:06 UTC, bulbetski commented on internal/controller/httpv1/url.go
> +func NewURLRoutes(
Вот эта вся шляпа должна быть частью контроллера. То есть твой app должен стать сервисным слоем или слоем контроллера, как угодно можно назвать. В нем будет роутер итд, что позволит не прокидывать юзкейсы в методы настройки рутов и сделает код чище и понятнее (как и было задумано)

2024-11-28 00:06 UTC, bulbetski commented on internal/controller/httpv1/url.go
> +	urlObj, err := ur.uuc.SaveURL(r.Context(), url, ur.getUserUUIDFromRequest(r))
ок ли нам ситуация, когда мы сохраняем пустой урл? может лучше сначала попытаться получить урл из getUserUUIDFromRequest, потом проверить его наличие и только после этого делать SaveURL с НЕпустым uuid

2024-11-28 00:06 UTC, bulbetski commented on internal/controller/httpv1/url.go
> +	udc *usecase.URLDeleteUseCase
лучше не экономить на названиях переменных. Дальше в самом коде как-то забывается по мере прочтения, что есть что. Опять же стоит объенить все это дело в один юзкейс и обозвать urlUc

2024-11-28 00:06 UTC, bulbetski commented on internal/usecase/urldelete.go
> +func (ud *URLDeleteUseCase) worker() {
Воркер пул должен быть отдельной структурой, который принимает на вход job или task. Он делает work. Лучше всего реализовать дженерик воркер пул в отдельном пакете и использовать его внутри твоего юзкейса. 

В структуре воркерпула будет кол-во воркеров и канал с джобами. Воркеры будут забирать эти джобы из канала и что-то делать с входными данными

2024-11-28 00:06 UTC, bulbetski commented on internal/usecase/urldelete.go
> +			ud.wg.Add(1)
Лучше это делать внутри функции создания воркера

2024-11-28 00:06 UTC, bulbetski commented on internal/usecase/urldelete.go
> +		ud.wg.Wait()
wg.Wait() внутри Close делает вызов блокирующим, что может быть неожиданным. Надо подумать, что с этим можно сделать

2024-11-28 00:06 UTC, bulbetski commented on internal/usecase/urldelete.go
> +	ud.urlDeleteItemsCh = make(chan *URLDeleteItem, urlDeleteItemsChanSize)
Канал urlDeleteItemsCh создаётся заново в Reset, но нигде не гарантируется отсутствие активных горутин, которые могут к нему обращаться. Нужно обеспечить безопасное завершение всех воркеров перед созданием нового канала

2024-11-30 17:02 UTC, llravell commented on internal/usecase/urldelete.go
> +	ud.urlDeleteItemsCh = make(chan *URLDeleteItem, urlDeleteItemsChanSize)
Добавил здесь `wg.Wait`, чтобы дождаться завершения всех горутин.
Перед отправкой в канал докинул еще проверку с атомиком, чтобы никто случайно не начал писать в закрытый канал

2024-11-30 17:02 UTC, llravell commented on internal/usecase/urldelete.go
> +		ud.wg.Wait()
Поправил

2024-11-30 19:01 UTC, llravell commented on internal/controller/httpv1/url.go
> +func NewURLRoutes(
Вот эту штуку не совсем понял. Имеешь ввиду разделять обработчики и конфигурацию роутера?
Такой принцип построение роутов подглядел в теплейтах:
- [go-clean-template](https://github.com/evrone/go-clean-template)
- [go-clean-arch](https://github.com/bxcodec/go-clean-arch)

Сейчас чуть отрефакторил: завязался не на юзкейсы, а на интерфейсы

2024-11-30 19:03 UTC, llravell commented on internal/app/app.go
> +	usecase.URLDeleteRepo
Спасибо большое за такую подробную обратную связь!
Это была первая попытка в чистую архитектуру :)

Отферакторил по твоим замечаниям, надеюсь все правильно понял

2024-12-03 04:02 UTC, bulbetski requested changes
Всё круто исправил. Осталось по мелочи

Еще советы по неймингу: Действие + название сущности
Пример:
вместо Get -- GetURL итд

2024-12-03 04:02 UTC, bulbetski commented on internal/app/app.go
> +	urlDeleteUseCase *usecase.URLDeleteUseCase
Можно объединить в 1 юзкейс опять же

2024-12-03 04:02 UTC, bulbetski commented on internal/app/app.go
>  	serverNorify := make(chan error, 1)
опечатка

2024-12-03 04:02 UTC, bulbetski commented on internal/rest/url.go
> +	urlDeleteUC URLDeleteUseCase
Надо объединить

2024-12-03 04:02 UTC, bulbetski commented on internal/rest/url.go
> +	urlDeleteUC URLDeleteUseCase,
По-прежнему надо сделать chi.Router частью твоего сервисного слоя, и сделать все функциями методами этой структуры. Ну и соответственно не передавать юзкейсы в эти методы -- они будут частью структуры

2024-12-03 04:02 UTC, bulbetski commented on internal/rest/url.go
> +	if err != nil || url == "" {
всегда сначала хэндлим ошибку

2024-12-03 04:02 UTC, bulbetski commented on internal/rest/url.go
> +			w.WriteHeader(http.StatusConflict)
нужен return

2024-12-03 04:02 UTC, bulbetski commented on internal/rest/url.go
> +	}
в каждом из условий и в конце фукнции стоит писать return'ы для консистентности

2024-12-03 04:02 UTC, bulbetski commented on pkg/workerpool/workerpool.go
> +	wp.wg.Add(1)
Метод worker вызывает wp.wg.Add(1) внутри каждой горутины. Если воркер пул останавливается (Close) до того, как все воркеры будут запущены, это может привести к некорректной работе WaitGroup (например, negative counter). Нужно добавить wp.wg.Add до запуска всех горутин в ProcessQueue.

2024-12-03 04:02 UTC, bulbetski commented on pkg/workerpool/workerpool.go
> +func (wp *WorkerPool[W]) ProcessQueue(ctx context.Context) {
Если ProcessQueue вызывается с контекстом, который уже отменен, горутины все равно будут запущены. Нужно проверять ctx.Done() перед запуском воркеров

2024-12-03 04:02 UTC, bulbetski commented on pkg/workerpool/workerpool.go
> +func (wp *WorkerPool[W]) Close() error {
При вызове Close, если канал задач закрывается, текущие горутины могут не завершить выполнение, если worksChan все еще содержит задачи.

2024-12-03 04:02 UTC, bulbetski commented on internal/usecase/url.go
> +	return uc.repo.GetByUserUUID(ctx, userUUID)
GetByUserUUID не оч информативно. Назови аналогично методу UC

2024-12-03 04:02 UTC, bulbetski commented on internal/usecase/urldelete.go
> +	if err != nil {
можно 
if err != nil { 
// ...
return
}
// ...
return

2024-12-03 04:02 UTC, bulbetski commented on internal/usecase/urldelete.go
> +func (w *URLDeleteWork) Do(ctx context.Context) {
Контекст ctx передается в метод Do, но он может быть отменен или неактивен на момент выполнения задачи, что приведет к непредсказуемому поведению. Нужно использовать контекст, передаваемый пулом воркеров, чтобы обеспечить контроль жизненного цикла задачи.

2024-12-03 19:20 UTC, llravell commented on pkg/workerpool/workerpool.go
> +	wp.wg.Add(1)
Переместил `Add` перед вызовом горутины, надеюсь правильно понял

2024-12-03 19:21 UTC, llravell commented on pkg/workerpool/workerpool.go
> +func (wp *WorkerPool[W]) ProcessQueue(ctx context.Context) {
Добавил тут обработку через `select`

2024-12-03 19:23 UTC, llravell commented on internal/usecase/urldelete.go
> +func (w *URLDeleteWork) Do(ctx context.Context) {
Я внутри воркера добавил обработку через `select`, если контекст отменяется, то `Do` не будет вызываться.
Но это если я правильно понял как это работает, пока тяжеловато представлять в голове многопоточное приложение))

2024-12-03 21:08 UTC, llravell commented on pkg/workerpool/workerpool.go
> +func (wp *WorkerPool[W]) ProcessQueue(ctx context.Context) {
UPD: пришлось тут упростить и избавиться от контекста. Намучался с тестами, почему-то они падают если стопануть воркеров раньше времени. Видимо количество потоков в тестах меньше чем количество воркеров и часть их них не успевает удалить урлы

2024-12-04 10:42 UTC, bulbetski requested changes
Можно сделать следующую структуру

internal/url -- основной пакет 
internal/url/usecase -- тут структура и файлы юзкейса

internal/url/repository -- тут все репозитории
internal/url/repository/memory
internal/url/repository/postgres

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_memo.go
> +func (u *URLMemoRepo) GetUserURLS(_ context.Context, userUUID string) ([]*entity.URL, error) {
Щас че-то подумал. А может ли быть асинхронный доступ к URLMemoRepo? Если да, то все операции надо обложить локами через мьютекс. Да и в целом это хорошая пратика -- делать взаимодействия с мапой thread-safe в веб-сервисах

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_psql.go
> +func (u *URLDatabaseRepo) Store(ctx context.Context, url *entity.URL) (*entity.URL, error) {
тут все ресивереры надо переименовать на r, так-как это всё-таки в первую очередь репо, а не url

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_psql.go
> +package repo
для memo и postgres хранилищ и юзкейсов можно сделать разделение по пакетам, ну и файлы будут тогда repo/memo/url, repo/postgres/url

Это рекомендация, это не обязательно

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_psql.go
> +	}
в цикле инсертить плохо, в случае большого количества запись это дает сильную нагрузку на базу. Нужно придумать хэлпер, который поможет сделать 1 большой инсерт или инсерт батчами (ну по 1000 штук, к примеру), но никак не по одной

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_psql.go
> +func (u *URLDatabaseRepo) Get(ctx context.Context, hash string) (*entity.URL, error) {
GetURL

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_psql.go
> +func (u *URLDatabaseRepo) StoreMultiple(ctx context.Context, urls []*entity.URL) error {
StoreMultipleURLs

2024-12-04 10:42 UTC, bulbetski commented on internal/repo/url_psql.go
> +func (u *URLDatabaseRepo) DeleteMultiple(ctx context.Context, userUUID string, urlHashes []string) error {
DeleteMultipleURLs

2024-12-04 10:42 UTC, bulbetski commented on internal/rest/router.go
> +}
Да, суть супер-правильная, но роутер это всё-таки твой chi.Router. Как будто все это должен содержать твой app, в котором будет еще и chi.Router

2024-12-04 10:42 UTC, bulbetski commented on internal/rest/router.go
> +	healthUseCase *usecase.HealthUseCase
Вместо структур должны быть интерфейсы

2024-12-04 10:42 UTC, bulbetski commented on cmd/shortener/main.go
> +		urlDeleteWorkerPool.Close()
Не обрабатываем ошибку

2024-12-04 21:00 UTC, bulbetski reviewed
Все норм исправил. В дальнейшем рекомендую пробрасывать интерфейсы вместо структур в другие структуры. Так и замокать можно, и разные инстансы реализующие одни и те же интерфейсы

2024-12-07 12:59 UTC, merged