Iter 5
llravell/go-shortener pull request #5
Opened 2024-10-06 09:37 UTC by llravell

2024-10-06 09:42 UTC, llravell commented on internal/api/handlers.go
> +type URLStorage interface {
Стоит ли интерфейсы зависимостей размещать в том же файле? Есть какие-то хорошие практики на этот счет?

2024-10-07 13:59 UTC, arttet commented on internal/api/handlers.go
> +type URLStorage interface {
https://github.com/evrone/go-clean-template/blob/master/internal/usecase/interfaces.go

2024-10-07 14:08 UTC, arttet requested changes
- [x] Split the application into layers
https://github.com/golang-standards/project-layout
https://medium.com/@deanrubin/the-three-layered-architecture-fe30cb0e4a6#:~:text=The%20presentation%20layer%20is%20the,Update%20or%20Delete)%20operation%20flow.
- [ ] Please integrate CodeCov https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- [x] Please read and use the Conventional Commits specification https://www.conventionalcommits.org/en/v1.0.0/
- [ ] Please integrate the linter https://github.com/golangci/golangci-lint-action
- [x] Please delete deprecated constraints in CI
https://github.com/llravell/go-shortener/blob/bd734cd734d03b0eabad2342bdc49eb5e74810a7/.github/workflows/shortenertest.yml#L65

2024-10-07 14:08 UTC, arttet commented on cmd/shortener/main.go
> +func runServer(c *config.Config) error {
[SUGGESTION] If I were you, I would move it to the `app` package.
https://github.com/golang-standards/project-layout/tree/master/internal/app/_your_app_

2024-10-07 14:08 UTC, arttet commented on internal/api/handlers.go
> +func makeSaveURLHandler(s URLStorage, hg HashGenerator, baseAddr string) http.HandlerFunc {
[CHANGE REQUEST] It should be a method.

2024-10-07 14:08 UTC, arttet commented on internal/api/handlers.go
> +func makeResolveURLHandler(s URLStorage) http.HandlerFunc {
[CHANGE REQUEST] It should be a method.

2024-10-07 14:08 UTC, arttet commented on internal/api/router.go
> +func BuildRouter(s URLStorage, hg HashGenerator, baseAddr string) chi.Router {
```suggestion
func Router(s URLStorage, hg HashGenerator, baseAddr string) chi.Router {
```

2024-10-07 14:08 UTC, arttet commented on internal/config/parsers.go
> +func (up *unionParser) Parse() error {
[CLARIFICATION] Why do you need it?

2024-10-07 14:08 UTC, arttet commented on internal/api/handlers.go
> +		hash := hg.Generate(10)
[CHANGE REQUEST] This is a magic number.

2024-10-14 11:18 UTC, arttet requested changes
- [ ] Please recover autotests

2024-10-14 11:18 UTC, arttet commented on .github/workflows/shortenertest.yml
> -        run: |
[CHANGE REQUEST] Please revert these changes. You have to run these tests.

2024-10-14 11:18 UTC, arttet commented on .github/workflows/test-coverage.yml
> +          go-version: '1.22'
```suggestion
          go-version: stable
```

2024-10-14 11:18 UTC, arttet commented on .github/workflows/test-coverage.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v4
```

2024-10-14 11:18 UTC, arttet commented on .github/workflows/test-coverage.yml
> +        uses: codecov/codecov-action@v3
```suggestion
        uses: codecov/codecov-action@v4
```

2024-10-14 12:02 UTC, arttet approved these changes

2024-10-14 12:02 UTC, arttet commented on internal/controller/httpv1/url_test.go
> +	"github.com/llravell/go-shortener/internal/usecase"
[CHANGE REQUEST] Please sort imports
https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-10-14 14:17 UTC, llravell commented on internal/controller/httpv1/url_test.go
> +	"github.com/llravell/go-shortener/internal/usecase"
Они вроде корректно отсортированы, поставил goimports, он не стал менять тут порядок

2024-10-14 14:17 UTC, merged