Iter9: backup
llravell/go-shortener pull request #9
Opened 2024-10-30 05:25 UTC by llravell

2024-10-30 16:24 UTC, llravell commented on internal/controller/httpv1/middleware/middleware_test.go
> +package middleware
Подходящее ли тут имя для файла с утилитами для тестирования? Есть какие-то практики как такие тестовые утилиты лучше хранить в рамках пакета/всего проекта?

2024-10-30 16:27 UTC, llravell commented on internal/usecase/repo/urlbackup.go
> +	fs := afero.NewOsFs()
Пришлось заюзать пакет, который абстрагирует работу с fs, чтобы протестировать. Не нашел более удобного способа мокать fs

2024-10-31 13:05 UTC, arttet commented on internal/controller/httpv1/middleware/middleware_test.go
> +package middleware
This is fine.

2024-10-31 13:05 UTC, arttet commented on internal/usecase/repo/urlbackup.go
> +	fs := afero.NewOsFs()
Why do you need to mock it?

2024-10-31 13:14 UTC, arttet requested changes

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    - varnamelen
[CHANGE REQUEST] Please enable it.

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    - wrapcheck
[CHANGE REQUEST] Please enable it.

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    - gochecknoglobals
[CHANGE REQUEST] Please enable it.

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    - reassign
[CHANGE REQUEST] Please enable it.

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    - funlen
[CHANGE REQUEST] Please enable it.

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    - noctx
[CHANGE REQUEST] Please enable it.

2024-10-31 13:14 UTC, arttet commented on .golangci.yml
> +    excludes:
[CHANGE REQUEST] Please remove it.

2024-10-31 13:14 UTC, arttet commented on Makefile
> +	go run cmd/shortener/main.go
```suggestion
.PHONY: run
run: ### run app in dev mode
    go run cmd/shortener/main.go
```

2024-10-31 13:14 UTC, arttet commented on internal/controller/httpv1/middleware/middleware_test.go
> +package middleware
```suggestion
package middleware_test
```

2024-10-31 13:14 UTC, arttet commented on internal/controller/httpv1/router.go
> +func NewRouter(u *usecase.URLUseCase, l zerolog.Logger, baseAddr string) *chi.Mux {
[SUGGESTION] `Logger` should be the latest parameter.

2024-10-31 13:14 UTC, arttet commented on internal/controller/httpv1/url.go
> +		Result: fmt.Sprintf("%s/%s", ur.baseAddr, urlObj.Short),
[CHANGE REQUEST] This is a business logic here.

2024-10-31 13:14 UTC, arttet commented on logger/logger.go
> +var log zerolog.Logger
[CHANGE REQUEST] Please don't use global variables.

2024-11-01 12:09 UTC, llravell commented on internal/usecase/repo/urlbackup.go
> +	fs := afero.NewOsFs()
Не хочется в автотестах по настоящему читать и писать в файлы. Или это нормальная история?

2024-11-01 12:12 UTC, llravell commented on logger/logger.go
> +var log zerolog.Logger
Так я же тут хочу создавать только один инстанс логгера, без глобальной переменной как будто не получится

2024-11-01 13:30 UTC, llravell commented on logger/logger.go
> +var log zerolog.Logger
Тут они к тому же доступны только внутри пакета, кажется это не очень опасно

2024-11-02 10:18 UTC, arttet commented on logger/logger.go
> +var log zerolog.Logger
You can do it.

2024-11-02 10:19 UTC, arttet commented on logger/logger.go
> +var log zerolog.Logger
> Тут они к тому же доступны только внутри пакета, кажется это не очень опасно

It doesn't matter.
https://github.com/uber-go/guide/blob/master/style.md#avoid-mutable-globals

2024-11-02 10:27 UTC, arttet commented on .golangci.yml
> +    min-name-length: 2
```suggestion
    min-name-length: 3
```

2024-11-02 10:27 UTC, arttet commented on internal/controller/httpv1/url_test.go
>  type MockRepo struct {
[CHANGE REQUEST] You should use code gen here

2024-11-02 10:27 UTC, arttet commented on logger/logger.go
> +	if logFile != nil {
[CHANGE REQUEST] This is unsafe.

2024-11-02 10:27 UTC, arttet commented on internal/app/app.go
> +	logger.Shutdown()
You have to use `defer`.

2024-11-02 10:27 UTC, arttet commented on internal/usecase/repo/urlbackup.go
> +	fs := afero.NewOsFs()
This is too strange. Up to you.

2024-11-02 10:27 UTC, arttet commented on logger/logger.go
> +var log zerolog.Logger
Up to you.

2024-11-03 13:13 UTC, merged